
# Global options
baseURL = "/"
canonifyURLs = true
copyright = "© 2024 by Bastian Seifert. <a href='/privacy'>Privacy policy</a>."
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
theme = "barks"
title = "Bastian Seifert"



# Main menu
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Projects"
    url  = "/projects"
    weight = 2
[[menu.main]]
    name = "Publications"
    url  = "/publications"
    weight = 3
[[menu.main]]
    name = "Blog"
    url  = "/posts"
    weight = 4



# Customization options
[params]

    [params.head]
        author = "Bastian Seifert"
        custom_css = ""
        description = "Software Engineer, Scientist, Consultant"
        keywords = ["Rust", "Graph Signal Processing", "Database Engines", "AI", "Causality"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
        title_font = "Bree Serif"
        body_font = "Source Sans Pro"

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#333333"
        link_color = "#60c17d"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:seifert.bastian@protonmail.com"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/bastian-seifert"
            weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar-square"
            url = "https://scholar.google.com/citations?user=JHwQad4AAAAJ&hl=de"
            weight = 3
        [params.social.linkedin]
            name = "LinkedIn"
            class = "fab fa-linkedin"
            url = "https://www.linkedin.com/in/bastian-seifert-91b29b56/"
            weight = 4
        [params.social.orcid]
            name = "ORCID iD"
            class = "fab fa-orcid"
            url = "https://orcid.org/0000-0002-2207-8285"
            weight = 5



# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'
